# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wikipedia.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wikipedia.proto',
  package='topicspace.corpus.wikipedia',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fwikipedia.proto\x12\x1btopicspace.corpus.wikipedia\"7\n\x0b\x43ontributor\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\x12\n\n\x02ip\x18\x03 \x01(\t\"\xc4\x01\n\x08Revision\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08parentid\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12=\n\x0b\x63ontributor\x18\x04 \x01(\x0b\x32(.topicspace.corpus.wikipedia.Contributor\x12\r\n\x05minor\x18\x05 \x01(\x08\x12\r\n\x05model\x18\x06 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x07 \x01(\t\x12\x0c\n\x04sha1\x18\x08 \x01(\t\x12\x0c\n\x04text\x18\t \x01(\t\"~\n\x04Page\x12\r\n\x05title\x18\x01 \x01(\t\x12\n\n\x02ns\x18\x02 \x01(\x03\x12\n\n\x02id\x18\x03 \x01(\x03\x12\x16\n\x0eredirect_title\x18\x04 \x01(\t\x12\x37\n\x08revision\x18\x05 \x03(\x0b\x32%.topicspace.corpus.wikipedia.Revisionb\x06proto3')
)




_CONTRIBUTOR = _descriptor.Descriptor(
  name='Contributor',
  full_name='topicspace.corpus.wikipedia.Contributor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='topicspace.corpus.wikipedia.Contributor.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='topicspace.corpus.wikipedia.Contributor.id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='topicspace.corpus.wikipedia.Contributor.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=103,
)


_REVISION = _descriptor.Descriptor(
  name='Revision',
  full_name='topicspace.corpus.wikipedia.Revision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='topicspace.corpus.wikipedia.Revision.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parentid', full_name='topicspace.corpus.wikipedia.Revision.parentid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='topicspace.corpus.wikipedia.Revision.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contributor', full_name='topicspace.corpus.wikipedia.Revision.contributor', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='topicspace.corpus.wikipedia.Revision.minor', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='topicspace.corpus.wikipedia.Revision.model', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='topicspace.corpus.wikipedia.Revision.format', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sha1', full_name='topicspace.corpus.wikipedia.Revision.sha1', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='topicspace.corpus.wikipedia.Revision.text', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=302,
)


_PAGE = _descriptor.Descriptor(
  name='Page',
  full_name='topicspace.corpus.wikipedia.Page',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='topicspace.corpus.wikipedia.Page.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ns', full_name='topicspace.corpus.wikipedia.Page.ns', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='topicspace.corpus.wikipedia.Page.id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redirect_title', full_name='topicspace.corpus.wikipedia.Page.redirect_title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='revision', full_name='topicspace.corpus.wikipedia.Page.revision', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=430,
)

_REVISION.fields_by_name['contributor'].message_type = _CONTRIBUTOR
_PAGE.fields_by_name['revision'].message_type = _REVISION
DESCRIPTOR.message_types_by_name['Contributor'] = _CONTRIBUTOR
DESCRIPTOR.message_types_by_name['Revision'] = _REVISION
DESCRIPTOR.message_types_by_name['Page'] = _PAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Contributor = _reflection.GeneratedProtocolMessageType('Contributor', (_message.Message,), dict(
  DESCRIPTOR = _CONTRIBUTOR,
  __module__ = 'wikipedia_pb2'
  # @@protoc_insertion_point(class_scope:topicspace.corpus.wikipedia.Contributor)
  ))
_sym_db.RegisterMessage(Contributor)

Revision = _reflection.GeneratedProtocolMessageType('Revision', (_message.Message,), dict(
  DESCRIPTOR = _REVISION,
  __module__ = 'wikipedia_pb2'
  # @@protoc_insertion_point(class_scope:topicspace.corpus.wikipedia.Revision)
  ))
_sym_db.RegisterMessage(Revision)

Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), dict(
  DESCRIPTOR = _PAGE,
  __module__ = 'wikipedia_pb2'
  # @@protoc_insertion_point(class_scope:topicspace.corpus.wikipedia.Page)
  ))
_sym_db.RegisterMessage(Page)


# @@protoc_insertion_point(module_scope)
